name: Build and deploy style files
on:
  pull_request_target:
    types:
      - closed
  push:
    branches:
      - "release_5-4"
      - "release_6"
      - "release_7"
      - "release_8"
      - "trunk"

jobs:
  if_merged:
    if: |
      github.event.pull_request.merged == true ||
      github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      all: ${{ steps.changes.outputs.all }}
    steps:
      - name: Branch
        run: echo ${GITHUB_REF##*/}
      - name: Env
        run: echo "$ENV_VARIABLE"
#      - name: Style to Repo
#        run: CI/Style-To-Repo/build-and-deploy.sh ${GITHUB_REF##*/}